name: Build and publish to pages

on:
  push:
    branches:
      - master  # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - name: Enable pnpm
        run: corepack enable pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: CNAME
        run: echo "b.soopy.moe" > public/CNAME
      - name: keybase
        run: |
          mkdir -p public/.well-known/
          cp ./keybase.txt ./public/.well-known/keybase.txt
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
